name: Docker Compose Build

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'docker-compose.yml'
      - '**/Dockerfile'
  push:
    branches: [ master ]
    paths:
      - 'docker-compose.yml'
      - '**/Dockerfile'

jobs:
  docker-compose-build:
    name: Docker Compose Build Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate docker-compose.yml
        run: docker-compose config
        
      - name: Build with docker-compose
        run: docker-compose build --no-cache

      - name: Run docker-compose
        run: |
          docker-compose up -d
          sleep 30
          
      - name: Check running containers
        run: docker-compose ps
        
      - name: Check containers health
        run: |
          docker-compose ps -q | xargs docker inspect --format='{{.State.Health.Status}}' || true
          
      - name: Show container logs
        run: docker-compose logs
        if: always()
        
      - name: Stop containers
        run: docker-compose down -v
        if: always() 